name: Lint and check
on: [ pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      # v4
      - uses: chartboost/ruff-action@e18ae971ccee1b2d7bbef113930f00c670b78da4
      # v1
      - uses: chartboost/ruff-action@e18ae971ccee1b2d7bbef113930f00c670b78da4 # v1
        with:
          args: 'format --check'
