name: Lint and check
on: [ pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Run ruff linter:
      - uses: chartboost/ruff-action@v1
      # Run ruff linter for formatting:
      - uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'
